services:
  mongo:
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"

  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

